--- 
abstract: GitHub Command Tools
author: 
  - Fayland Lam <fayland@gmail.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.006
license: perl
name: App-GitHub
requires: 
  JSON::XS: 2.232
  Moose: 0
  Net::GitHub: 0.09
  Term::ReadLine: 0
resources: 
  repository: git://github.com/fayland/perl-app-github.git
version: 0.05
